### ISSUE TITLE
关于编号的一些小建议

### ISSUE THREAD

**Issue by dreamMilk** [LittleNewton/Equation_and_Codebox#13]
对于编号的格式设置一个自定义的选项，有的文章公式编号不需要按章节划分，只有一位编号，不需要X-Y的格式，每次编号都需要进行删除，比较繁琐，不知道能不能改进。

**Comment by LittleNewton** [comment]
Hi,

我将用尽可能简单的方式实现这个 feature.

**Comment by LittleNewton** [comment]
已经在 Release 0.5  预览版完成该功能。

参见：

https://github.com/LittleNewton/Equation_and_Codebox/commit/f2a6264823e11820a578f0656ba5680a03260015

**Comment by dreamMilk** [comment]
作者大大，我还有一个小要求，使用插件生成的表格公式字体好像被默认设置为Latin Modern Math 字体，即使其他字体设置为公式字体默认值，新建表格公式时仍然是Latin Modern Math 字体，这个字体能够给出选项吗，因为需要用到类Times New Rome字体，可能需要每个进行手动更改，有点繁琐

**Comment by LittleNewton** [comment]
对于新 feature，请提交新 issue.
