### ISSUE TITLE
页边距较大时公式编号超出页面范围

### ISSUE THREAD

**Issue by kiwi1944** [LittleNewton/Equation_and_Codebox#4]
hi，
在使用过程中，设置word常规页边距（左右3.18cm），插入公式的编号已经完全超出了文字范围，在页边距外。猜测是包含编号和公式的表格长度不能随页面文字宽度自动变换，需要手动调整，普适性不好，调整起来比较麻烦。希望能有所更新。
注：使用的是0.2版本，office2019。
![capture_20210511213841744](https://user-images.githubusercontent.com/65650692/117824746-4dd1b580-b2a1-11eb-994e-99238fc0dbe5.jpg)

**Comment by LittleNewton** [comment]
这个问题非常正确。

因为当时我写报告时，自定义的页边距就是左右各 20mm，所以就把数据写成固定大小了。改起来也不麻烦，获取一下页面的宽度和页边距，做一下减法即可。过几天我修改一下。

另外，可以将你的 Word 字体修改一下。[Latin Modern Math](http://www.gust.org.pl/projects/e-foundry/lm-math/download/latinmodern-math-1959.zip) 比较好看。

**Comment by kiwi1944** [comment]
提前感谢您的更新！

另外想请教一下，Latin Modern Math字体之前已安装，但是word中插入公式已经在下图这里选择默认Latin Modern Math，但是每次开启word还是Cambria Math字体，只有在新的word里重新设置，然后再插入公式才默认Latin Modern Math。如果打开一个新的word，还要重复这个设置过程。不知是否有办法可以解决？

以上问题是直接在word插入公式发生的，您的插件字体已经设计好，没有问题。
![capture_20210512130654562](https://user-images.githubusercontent.com/65650692/117921244-fd02a100-b322-11eb-9381-3443820fd3cc.jpg)

**Comment by LittleNewton** [comment]
@kiwi1944 

Word 的这个【公式选项】问题非常好解决，点击下图中的【默认值】即可。

![2021-05-12_205814](https://user-images.githubusercontent.com/17793356/117978923-f4cb5580-b364-11eb-9ca5-b3e82f7b84ff.png)

直接点击确定的话，下次打开 Word 不会生效。

**Comment by kiwi1944** [comment]
非常感谢！【公式选项】问题已解决！

**Comment by LittleNewton** [comment]
@kiwi1944 

9a234ab2412a908ac109e56ba18050e506046e51 之后，已经可以自动化识别版面宽度了。

**Comment by kiwi1944** [comment]
> 

感谢更新！
